package com.hipalsports.entity;

import java.io.Serializable;
import java.util.Date;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

@DatabaseTable(tableName = "friend_detail")
public class FriendDetail  implements Serializable {

	private static final long serialVersionUID = 3930627993984747603L;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column v_friend.id
	 *
	 * @mbggenerated
	 */
	@DatabaseField(id = true)
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column v_friend.user_id
	 *
	 * @mbggenerated
	 */
	@DatabaseField()
	private Integer userId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column v_friend.friend_user_id
	 *
	 * @mbggenerated
	 */
	@DatabaseField()
	private Integer friendUserId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column v_friend.status
	 *
	 * @mbggenerated
	 */
	@DatabaseField()
	private Integer status;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column v_friend.create_time
	 *
	 * @mbggenerated
	 */
	@DatabaseField()
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column v_friend.last_update_time
	 *
	 * @mbggenerated
	 */
	@DatabaseField()
	private Date lastUpdateTime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column v_friend.nick_name
	 *
	 * @mbggenerated
	 */
	@DatabaseField()
	private String nickName;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column v_friend.email
	 *
	 * @mbggenerated
	 */
	@DatabaseField()
	private String email;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column v_friend.phone
	 *
	 * @mbggenerated
	 */
	@DatabaseField()
	private String phone;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column v_friend.gender
	 *
	 * @mbggenerated
	 */
	@DatabaseField()
	private String gender;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column v_friend.logo_url
	 *
	 * @mbggenerated
	 */
	@DatabaseField()
	private String logoUrl;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column v_friend.signature
	 *
	 * @mbggenerated
	 */
	@DatabaseField()
	private String signature;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column v_friend.id
	 *
	 * @return the value of v_friend.id
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column v_friend.id
	 *
	 * @param id the value for v_friend.id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column v_friend.user_id
	 *
	 * @return the value of v_friend.user_id
	 *
	 * @mbggenerated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column v_friend.user_id
	 *
	 * @param userId the value for v_friend.user_id
	 *
	 * @mbggenerated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column v_friend.friend_user_id
	 *
	 * @return the value of v_friend.friend_user_id
	 *
	 * @mbggenerated
	 */
	public Integer getFriendUserId() {
		return friendUserId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column v_friend.friend_user_id
	 *
	 * @param friendUserId the value for v_friend.friend_user_id
	 *
	 * @mbggenerated
	 */
	public void setFriendUserId(Integer friendUserId) {
		this.friendUserId = friendUserId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column v_friend.status
	 *
	 * @return the value of v_friend.status
	 *
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column v_friend.status
	 *
	 * @param status the value for v_friend.status
	 *
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column v_friend.create_time
	 *
	 * @return the value of v_friend.create_time
	 *
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column v_friend.create_time
	 *
	 * @param createTime the value for v_friend.create_time
	 *
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column v_friend.last_update_time
	 *
	 * @return the value of v_friend.last_update_time
	 *
	 * @mbggenerated
	 */
	public Date getLastUpdateTime() {
		return lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column v_friend.last_update_time
	 *
	 * @param lastUpdateTime the value for v_friend.last_update_time
	 *
	 * @mbggenerated
	 */
	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column v_friend.nick_name
	 *
	 * @return the value of v_friend.nick_name
	 *
	 * @mbggenerated
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column v_friend.nick_name
	 *
	 * @param nickName the value for v_friend.nick_name
	 *
	 * @mbggenerated
	 */
	public void setNickName(String nickName) {
		this.nickName = nickName == null ? null : nickName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column v_friend.email
	 *
	 * @return the value of v_friend.email
	 *
	 * @mbggenerated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column v_friend.email
	 *
	 * @param email the value for v_friend.email
	 *
	 * @mbggenerated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column v_friend.phone
	 *
	 * @return the value of v_friend.phone
	 *
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column v_friend.phone
	 *
	 * @param phone the value for v_friend.phone
	 *
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column v_friend.gender
	 *
	 * @return the value of v_friend.gender
	 *
	 * @mbggenerated
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column v_friend.gender
	 *
	 * @param gender the value for v_friend.gender
	 *
	 * @mbggenerated
	 */
	public void setGender(String gender) {
		this.gender = gender == null ? null : gender.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column v_friend.logo_url
	 *
	 * @return the value of v_friend.logo_url
	 *
	 * @mbggenerated
	 */
	public String getLogoUrl() {
		return logoUrl;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column v_friend.logo_url
	 *
	 * @param logoUrl the value for v_friend.logo_url
	 *
	 * @mbggenerated
	 */
	public void setLogoUrl(String logoUrl) {
		this.logoUrl = logoUrl == null ? null : logoUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column v_friend.signature
	 *
	 * @return the value of v_friend.signature
	 *
	 * @mbggenerated
	 */
	public String getSignature() {
		return signature;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column v_friend.signature
	 *
	 * @param signature the value for v_friend.signature
	 *
	 * @mbggenerated
	 */
	public void setSignature(String signature) {
		this.signature = signature == null ? null : signature.trim();
	}
}