package com.hipalsports.entity;

import java.io.Serializable;
import java.util.Date;

public class UserInfo implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.userId
	 * @mbggenerated
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.nickName
	 * @mbggenerated
	 */
	private String nickName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.email
	 * @mbggenerated
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.phone
	 * @mbggenerated
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.password
	 * @mbggenerated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.gender
	 * @mbggenerated
	 */
	private Integer gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.logoUrl
	 * @mbggenerated
	 */
	private String logoUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.signature
	 * @mbggenerated
	 */
	private String signature;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.createTime
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_info.lastUpdateTime
	 * @mbggenerated
	 */
	private Date lastUpdateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.userId
	 * @return  the value of user_info.userId
	 * @mbggenerated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.userId
	 * @param userId  the value for user_info.userId
	 * @mbggenerated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.id
	 * @return  the value of user_info.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.id
	 * @param id  the value for user_info.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.nickName
	 * @return  the value of user_info.nickName
	 * @mbggenerated
	 */
	public String getNickName() {
		return nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.nickName
	 * @param nickName  the value for user_info.nickName
	 * @mbggenerated
	 */
	public void setNickName(String nickName) {
		this.nickName = nickName == null ? null : nickName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.email
	 * @return  the value of user_info.email
	 * @mbggenerated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.email
	 * @param email  the value for user_info.email
	 * @mbggenerated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.phone
	 * @return  the value of user_info.phone
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.phone
	 * @param phone  the value for user_info.phone
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.password
	 * @return  the value of user_info.password
	 * @mbggenerated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.password
	 * @param password  the value for user_info.password
	 * @mbggenerated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.gender
	 * @return  the value of user_info.gender
	 * @mbggenerated
	 */
	public Integer getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.gender
	 * @param gender  the value for user_info.gender
	 * @mbggenerated
	 */
	public void setGender(Integer gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.logoUrl
	 * @return  the value of user_info.logoUrl
	 * @mbggenerated
	 */
	public String getLogoUrl() {
		return logoUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.logoUrl
	 * @param logoUrl  the value for user_info.logoUrl
	 * @mbggenerated
	 */
	public void setLogoUrl(String logoUrl) {
		this.logoUrl = logoUrl == null ? null : logoUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.signature
	 * @return  the value of user_info.signature
	 * @mbggenerated
	 */
	public String getSignature() {
		return signature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.signature
	 * @param signature  the value for user_info.signature
	 * @mbggenerated
	 */
	public void setSignature(String signature) {
		this.signature = signature == null ? null : signature.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.createTime
	 * @return  the value of user_info.createTime
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.createTime
	 * @param createTime  the value for user_info.createTime
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_info.lastUpdateTime
	 * @return  the value of user_info.lastUpdateTime
	 * @mbggenerated
	 */
	public Date getLastUpdateTime() {
		return lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_info.lastUpdateTime
	 * @param lastUpdateTime  the value for user_info.lastUpdateTime
	 * @mbggenerated
	 */
	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	private static final long serialVersionUID = -3170322250039228386L;
}